name: BigBrother
main: shoghicp\BigBrother\BigBrother
load: STARTUP
author: BigBrotherTeam
version: 1.7.0-beta
api: [5.0.0]
description: "A Minecraft Java -> Minecraft Bedrock protocol translator for PMMP."
website: https://github.com/KingRainbow44/BigBrother-1
